name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/the_quick_meal.png
  - assets/images/screenshot_20240825192213.png
  - assets/vectors/notch_5_x2.svg
  - assets/vectors/ellipse_8_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/mobile_signal_13_x2.svg
  - assets/vectors/image_15_x2.svg
  - assets/images/google_1.png
  - assets/images/facebook_1.png
  - assets/images/apple_1.png
  - assets/vectors/image_9_x2.svg
  - assets/vectors/bg_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/bg_4_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/bg_2_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/notch_15_x2.svg
  - assets/vectors/mobile_signal_9_x2.svg
  - assets/vectors/bg_1_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/images/royal_durbar_restro_1.jpeg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/wifi_20_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/notch_17_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/image_20_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/mobile_signal_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/images/screenshot_20240825101833.png
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/notch_7_x2.svg
  - assets/vectors/mobile_signal_5_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/battery_8_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/image_x2.svg
  - assets/vectors/wifi_11_x2.svg
  - assets/images/facebook_1.png
  - assets/images/google_1.png
  - assets/images/apple_1.png
  - assets/vectors/battery_14_x2.svg
  - assets/vectors/mobile_signal_11_x2.svg
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/image_14_x2.svg
  - assets/vectors/bg_5_x2.svg
  - assets/vectors/bg_3_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/notch_13_x2.svg
  - assets/images/screenshot_20240824235722.png
  - assets/vectors/battery_19_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/notch_8_x2.svg
  - assets/vectors/mobile_signal_7_x2.svg
  - assets/vectors/image_19_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/images/the_quick_meal.png
  - assets/images/get_started.jpeg
  - assets/vectors/mobile_signal_16_x2.svg
  - assets/vectors/image_11_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/notch_14_x2.svg
  - assets/vectors/combined_shape_x2.svg
  - assets/vectors/wifi_10_x2.svg
  - assets/images/rectangle_43.png
  - assets/images/screenshot_20240825152913.png
  - assets/vectors/container_2_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/battery_12_x2.svg
  - assets/vectors/image_10_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/mobile_signal_4_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/wifi_15_x2.svg
  - assets/vectors/notch_11_x2.svg
  - assets/vectors/wifi_18_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/rectangle_53_x2.svg
  - assets/vectors/notch_9_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/battery_7_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/image_12_x2.svg
  - assets/vectors/mobile_signal_19_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/images/foodbank_australia_logo_760_ed_6_b_6_e_2_seeklogo_com.png
  - assets/images/the_quick_meal.png
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/wifi_19_x2.svg
  - assets/vectors/foodbank_australia_logo_760_ed_6_b_6_e_2_seeklogo_com_1_x2.svg
  - assets/vectors/mobile_signal_10_x2.svg
  - assets/vectors/image_5_x2.svg
  - assets/vectors/notch_3_x2.svg
  - assets/images/output_1.jpeg
  - assets/images/cafe_sydney_restaurant_at_dusk_credit_cafe_sydney_0.jpeg
  - assets/images/a_91_d_2953_d_22_c_4_d_1196024086377_e_9_ca_71131_x_450.jpeg
  - assets/images/royal_durbar_restro.png
  - assets/images/cold_beer.png
  - assets/images/fb_86662148_be_855_d_931_b_37_d_6_c_1_e_5_fcbe.jpeg
  - assets/images/output.jpeg
  - assets/images/download.jpeg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/notch_16_x2.svg
  - assets/vectors/image_6_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_150_x2.svg
  - assets/vectors/mask_group_1_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/mobile_signal_17_x2.svg
  - assets/vectors/wifi_13_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/mobile_signal_15_x2.svg
  - assets/vectors/notch_12_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/battery_18_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/image_17_x2.svg
  - assets/images/the_quick_meal.png
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/mobile_signal_14_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/mask_group_2_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/notch_1_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/image_16_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/battery_16_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/images/the_quick_meal.png
  - assets/vectors/battery_13_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/vector_151_x2.svg
  - assets/vectors/notch_6_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/mobile_signal_18_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/image_18_x2.svg
  - assets/images/screenshot_20240825152913.png
  - assets/vectors/wifi_12_x2.svg
  - assets/vectors/marker_1_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/notch_19_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/battery_6_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/image_13_x2.svg
  - assets/vectors/mobile_signal_20_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/battery_11_x2.svg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/mobile_signal_6_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/image_1_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_153_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/mask_group_x2.svg
  - assets/vectors/vector_140_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/notch_10_x2.svg
  - assets/vectors/wifi_14_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/images/the_quick_meal.png
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/image_4_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/notch_18_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/mobile_signal_2_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/vector_144_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/images/image.png
  - assets/images/royal_durbar_restro.png
  - assets/images/restaurant_logo_design_vector.jpeg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/mobile_signal_8_x2.svg
  - assets/vectors/notch_2_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/image_2_x2.svg
  - assets/vectors/battery_15_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/battery_10_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/image_7_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/notch_4_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/mobile_signal_3_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/images/istockphoto_1947047446612_x_612.jpeg
  - assets/vectors/mobile_signal_12_x2.svg
  - assets/vectors/notch_20_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/image_8_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/battery_17_x2.svg
  - assets/vectors/wifi_16_x2.svg
  - assets/images/apple_pay_1.png
  - assets/images/google_pay_1.png
  - assets/images/paypal_1.png
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/mobile_signal_1_x2.svg
  - assets/vectors/wifi_17_x2.svg
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/image_3_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/notch_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/battery_9_x2.svg
  - assets/vectors/vector_147_x2.svg

